src/App.js
=> Only enable google analytics if a certain env var is set

Dockerfile, README.md
=> Added dockerfile and instructions in readme

src/App.js, src/Components/Spectrogram/RulerSide.js, src/Components/Spectrogram/RulerTop.js, src/Components/Spectrogram/SpectrogramPage.js, src/Components/Spectrogram/TimeSelector.js, src/Utils/create_thumbnails.py, src/Utils/selector.js
fills the screen height, when you are scrolled all the way up at least
=> Flexible spectrogram height

src/Components/Spectrogram/ScrollBar.js, src/Components/Spectrogram/SpectrogramPage.js, src/Utils/selector.js
=> Show which tiles have been downloaded

.github/workflows/main_iqengineweb.yml
Correrct build to include only the byuoild folder
=> Correct build folder

.github/workflows/main_iqengineweb.yml
Add envitonment variables to build
=> Add environment variables

.github/workflows/main_iqengineweb.yml
Add envitonment variables to build
=> Corrrect build

.github/workflows/main_iqengineweb.yml
=> Add build quotes

.github/workflows/docker-release.yml
=> Registry_token

Dockerfile
Docker does not support you to copy only if the file exist...
=> Docker does not support contintional copy

.github/workflows/docker-release.yml, Dockerfile
Enable docker push of the image and adding descriptive labels.
=> Docker labels and enabling push

.github/release-drafter.yml, .github/workflows/docker-release.yml, Dockerfile
Publish a new image on every release.
=> Add new release for every push

.github/workflows/main_iqengineweb.yml, .github/workflows/most_recent_pr_iqengineweb.yml
=> rename workflows so they have unique names

client/src/Components/Spectrogram/SpectrogramPage.jsx
Fix alignment after previous spectogram changes
=> Sort alignment of tables

.github/workflows/docker-pre-release.yml, .github/workflows/docker-release.yml
Add the data as part of the pre-release tag to avoid conficts.
=> Add data to avoid pre-release conflicts

client/src/Components/Spectrogram/SettingsPane.jsx, client/src/Components/Spectrogram/SpectrogramPage.jsx
still using react-bootstrap but daisyui doesnt have any sliders like this...
=> Use sliders for magnitude max/min

client/src/Config.ts
=> Fix config error

.editorconfig, Makefile
Add a linter to the makefile so people can lint files locally.
=> Add make lint to lint your files locally

client/package-lock.json, client/package.json, client/vite.config.ts
=> Fix deploy to staging

client/src/Utils/sigmfStructure.ts, client/src/api/datasource/ApiClient.ts, client/src/api/datasource/BlobClient.ts, client/src/api/datasource/DataSourceClient.ts, client/src/api/datasource/LocalClient.ts
This PR adds a SigMF metadata structure object and then uses it in the Data Source clients.
=> Add types on the data source clients

client/src/Components/AutoSizeInput/AutoSizeInput.tsx, client/src/Components/DataTable/DataTable.tsx, client/src/Utils/rfFunctions.test.ts, client/src/Utils/rfFunctions.ts, client/src/index.css
Fixes issue where date doesn't display when working in nanoseconds/picoseconds
Before:
After:
=> Fix bug when working in nanosecond/picosecond

client/src/Components/RecordingsBrowser/File.tsx, client/src/Components/RecordingsBrowser/RecordingsBrowser.jsx, client/src/Components/RepoBrowser/LocalFileBrowser.jsx, client/src/Components/Spectrogram/DetectorPane.jsx, client/src/Components/Spectrogram/SettingsPane.jsx, client/src/Components/Spectrogram/SpectrogramPage.jsx, client/src/Sources/FetchMoreDataSource.ts, client/src/Utils/parseMeta.ts, client/src/api/config/queries.ts
Fix buiugs currently on Staging on the creation of new files.
=> Fix staging bugs on fetching data

client/src/Components/RepoBrowser/LocalFileBrowser.jsx, client/src/Components/Spectrogram/SpectrogramPage.jsx
Fix the validation in case the file loads really fast
=> Correct the validation of the first load

.gitignore, tiling/create_pmtiles.py, tiling/requirements.txt
The tiles look good in https://protomaps.github.io/PMTiles when you go to the "Tile Inspector" but in the main map view, when you zoom in, it doesn't seem like its actually displaying the zoomed in ones...  @PaulDFoster maybe you can figure out why,
=> Created pmtiles generation script

.gitignore, Makefile, __tests__/example.spec.ts, package-lock.json, package.json, playwright.config.ts
fixed api-related make targets
added make test target
This PR adds the framework for integration tests in the project. There are already integration tests using the pytest framework in the /api folder. This PR adds integration tests for the frontend and for end-to-end use cases in the __tests__ folder using the Playwright test system.
=> added playwright requirements to project

client/src/api/metadata/Queries.ts
=> Fix query spelling

client/src/Components/Spectrogram/SettingsPane.tsx
Remove's tick which is the bane of Gabe's life
https://github.com/IQEngine/IQEngine/assets/9397730/6a6acbe8-774b-4ea7-8302-ab526326c7c2
=> Remove tick

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/Components/RepoBrowser/AzureBlobBrowser.tsx
Add validation for blob storage in case there is incomplete data so we do not navidate with incomplete date.
=> Add blob validation

client/src/Components/Spectrogram/SpectrogramPage.tsx
=> fixed scrolling annotations bug

client/src/Components/Annotation/Actions.tsx, client/src/Components/Annotation/AnnotationList.tsx, client/src/Components/Annotation/__tests__/Actions.test.tsx, client/src/Components/DataTable/__tests__/DataTable.test.tsx, client/src/Components/RepoBrowser/RepositoryTile.tsx, client/src/Components/Spectrogram/SpectrogramPage.tsx
Adds an initial view of the annotations json view so you can edit the json directly, will be good to add further tweaks to ensure that it validates the annotation before updating globally
=> annotations-actions

infra/containerapp.bicep, infra/environment.bicep, infra/law.bicep, infra/main.bicep, infra/mongodb.bicep
This add the required template to deploy your own instance of IQEngine to Azure.
=> Add Bicep deployment infra.

client/src/Components/Annotation/Actions.tsx, client/src/Components/Annotation/AnnotationList.tsx, client/src/Components/Annotation/__tests__/Actions.test.tsx, client/src/Components/Annotation/__tests__/AnnotationList.test.tsx
Noticed the Annotations wasn't correctly updating when they had updated on the page, now this works correctly.
Before:
https://github.com/IQEngine/IQEngine/assets/9397730/d4fa378e-ef3d-4ed5-9457-e0ff541e2364
After:
https://github.com/IQEngine/IQEngine/assets/9397730/96a544aa-3332-4556-b9ea-abd91ed95484
=> Fix annotation not updating

client/src/Components/RepoBrowser/LocalFileBrowser.tsx, client/src/api/datasource/LocalClient.ts, client/src/api/iqdata/LocalClient.ts, client/src/api/metadata/LocalClient.ts, client/src/api/metadata/__tests__/LocalClient.test.tsx
Correct the bug when loading local files a single one or multiple.
=> Fix local files

client/src/api/config/queries.ts
Allows optional env var from the .env.
Change on error code to load an empty env var correcting attempt to load from the .env
=> Allow optional env var

.vscode/settings.json, client/src/Components/MetaViewer/MetaViewer.tsx, e2e/README.md
This fix the metaviewer load componeent when there is no metadata.
=> Add metaviewer fix and prettier config fix

client/src/Components/Spectrogram/SettingsPane.tsx, client/src/Components/Spectrogram/SpectrogramPage.tsx, client/src/Sources/FetchMoreDataSource.ts, client/src/api/iqdata/Queries.ts, client/src/api/iqdata/__tests__/Queries.test.tsx
This adds back again the capabilityn to add taps and python.
Still need to work on the refresh of the spectogram
=> Add python taps filter

client/src/Components/SignalGenerator/SignalGenerator.jsx
editing the main snippet wasnt working
=> Fixed Siggen

.vscode/launch.json
Adds launch configuration for front end debugging
=> Add debugger for front end

client/src/App.tsx
=> Use react router dom for other pages

client/src/Components/Spectrogram/ScrollBar.tsx, client/src/Components/Spectrogram/SettingsPane.tsx, client/src/Components/Spectrogram/Sidebar.tsx, client/src/Components/Spectrogram/TimeSelector.jsx
- Adds the ability to scroll through the spectrogram with the mouse wheel
- Fixes a problem with the selection cursors which allowed the start of the selection to be past the end
- Allows saving a selection of the spectrogram as a new .sigmf file (Currently slightly buggy, a large section of blank appears before any signal in the saved file)
=> Downloading selections of signal

api/main.py
This fix #206 
Fix the bug that woiuld not allow you to look at internal pages in the docker image.
=> Fix routing for internal pages

client/src/Components/RepoBrowser/RepositoryTile.tsx
Add missing behavious on the click to browse.
=> Fix button click handling

client/src/Components/Validator/Validator.tsx
=> Add language extension

e2e/playwright-pr.config.ts
Updates the staging URL for Playwright tests.
=> Update staging url

client/src/Components/Spectrogram/PluginsPane.tsx, client/src/Components/Validator/Validator.tsx, client/src/Utils/__tests__/rfFunctions.test.ts, client/src/Utils/rfFunctions.ts, e2e/README.md, plugins/README.md, plugins/src/lowpass_filter/lowpass_filter.py, plugins/src/plugins_api.py
=> start using base64 with plugins

client/src/Components/Spectrogram/SpectrogramPage.tsx
Small pr just to add mouse scroll capabilities to the spectrogram
=> Adding mouse scroll to the spectrogram

client/src/Components/Annotation/AnnotationList.tsx, client/src/Components/Annotation/AnnotationViewer.tsx, client/src/Components/AutoSizeInput/AutoSizeInput.tsx, client/src/Components/Metadata/MetaRaw.tsx, client/src/Components/Spectrogram/SpectrogramPage.tsx
Fixes the annotation viewer label not working
=> fix-for-annotations-viewer

client/src/Components/RepoBrowser/RepositoryAPITile.tsx
=> updated repo api tile to match normal repo tile

client/src/App.tsx
all this does is disable the displayInternalBranding.  i think hannah or someone else doesnt have prettier installed
=> disable displayInternalBranding for now

client/src/Components/Logo/Logo.tsx
=> make new logo even more fun

client/src/Components/Spectrogram/SpectrogramPage.tsx
Spectrogram wasn't rendering image correctly on window resize, this fixes that.
Before:
https://github.com/IQEngine/IQEngine/assets/9397730/82de8767-4894-4ca5-af7b-6cd1b212fd24
After:
https://github.com/IQEngine/IQEngine/assets/9397730/b4a96288-2438-4bce-ab62-978f53c0ab98
=> Fix screen location bug on resize

api/database/database.py, api/database/models.py, api/handlers/processors.py, api/main.py, api/tests/test_processors.py
Starting the support for multiple processors adding the configuration for it to the API
=> Add processors endpoint to API

.cspell.json, Makefile, README.md, api/database/database.py, api/tests/conftest.py, e2e/__tests__/confirm_API_data_browse.spec.ts, e2e/webServer.sh, tools/metadata_loader/README.md
also renamed FF_INMEMDB to IN_MEMORY_DB, not obvious was FF meant
=> Removed references to RFDX so as not to confuse people

client/src/Components/Spectrogram/PluginsPane.tsx, client/src/Components/Spectrogram/SettingsPane.tsx, client/src/Components/Spectrogram/Sidebar.tsx, client/src/Components/Spectrogram/SpectrogramPage.tsx, client/src/Utils/selector.ts
=> Remove automin/max

README.md
Updates the readme to describe the feature flags currently in use.
=> Update readme to include ff

.cspell.json, Makefile, client/src/pages/signalGenerator/SignalGenerator.tsx, e2e/README.md, e2e/__tests__/confirm_API_data_browse.spec.ts, e2e/__tests__/siggen.spec.ts, e2e/example.env, e2e/package-lock.json, e2e/package.json, e2e/teardown.sh, e2e/webServer.sh
Add a test for the siggen page. Test the operation of the page.
Along the way, it was necessary to change the alt text of the 4 images because they were all the same and that makes it difficult for playwright to find the right one. And, I added the hidden flag to the images because playwright can find it when it becomes visible easily.
Also removed rfdx references.
=> restore siggen test

client/src/api/config/queries.ts, client/src/hooks/useFeatureFlags.tsx
Tells the dev in the console what environment variables are being used and if there has been an error.
& the removal of a console.log leftover from previous development.
=> Add console logs for adding env variables

README.md, api/handlers/config.py, api/tests/test_api.py, client/src/Components/RepoBrowser/__tests__/RepoBrowser.test.tsx, client/src/api/config/queries.test.tsx, client/src/api/config/queries.ts, client/src/pages/spectrogram/components/PluginsPane.tsx, docker-compose-e2e.yml, docker-compose.yml, plugins/README.md
Dix a bug with plugins not being present.
=> Adding fix to invalid plugins config

infra/containerapp.bicep, infra/iqengine.json
=> Do not allow insecure

client/src/pages/spectrogram/components/PluginsPane.tsx
Correct bug in the plugins download.
=> Correct build plugins

e2e/__tests__/confirm_gnuradio.spec.ts
Add test for the metadata to the tasks test actions
=> Add check for metadata

plugins/README.md
adds instructions on how to write a plugin to the plugin readme
=> augment readme

client/README.md, client/src/store/reducers/ConnectionReducer.ts, client/src/store/reducers/LocalClientReducer.ts
Crerate the readme for file format and remove some dead code.
=> Document file structure

api/handlers/metadata.py
Adds geolocation query for a global.core:geolocation field. 
The global.core:geolocation field will contain a GeoJson point specification.
The query receives a longitude, a latitude and a radius in metres. The query looks for a documents with a global.core:geolocation specified point within the specified radius of the query point.
=> Add geolocation query

.github/workflows/docker-pre-release.yml, .github/workflows/docker-release.yml
Addd plugins build as part of the release and pre-release
=> Adding plugins container image

client/src/features/ui/auto-size-input/AutoSizeInput.tsx, client/src/pages/spectrogram/components/annotation/AnnotationList.tsx, client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.meta.json, client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx
Added commnents to the annotations
=> Add capability to add and view comments.

infra/containerapp.bicep, infra/iqengine.json
=> add sticky sessions to infra

api/handlers/datasources.py, api/handlers/iq.py, api/handlers/metadata.py, api/handlers/urlmapping.py
Update the API so that a null or missing data source SAS Token is taken to mean public access to a blob store rather than raise an error.
=> Public access blob store

client/src/api/utils/AzureBlob.ts, e2e/__tests__/confirm_API_data_browse.spec.ts, e2e/__tests__/confirm_api_datasource.spec.ts, e2e/__tests__/confirm_blob_datasource.spec.ts, e2e/__tests__/confirm_gnuradio.spec.ts, e2e/__tests__/confirm_siggen_card.spec.ts, e2e/__tests__/confirm_validator_card.spec.ts, e2e/__tests__/siggen.spec.ts, e2e/__tests__/trivial.spec.ts
Marks tests that are compatible with the CI pipeline so they can be run with a single command rather than listing them.
Fix "merge main branch" bug for sas token.
=> tag cicompatible tests

.github/workflows/run_playwright_tests.yml, client/src/api/utils/AzureBlob.ts, e2e/__tests__/confirm_API_data_browse.spec.ts, e2e/__tests__/confirm_api_datasource.spec.ts, e2e/__tests__/confirm_blob_datasource.spec.ts, e2e/__tests__/confirm_gnuradio.spec.ts, e2e/__tests__/confirm_siggen_card.spec.ts, e2e/__tests__/confirm_validator_card.spec.ts, e2e/__tests__/siggen.spec.ts, e2e/__tests__/trivial.spec.ts
reconfigure playwright workflow to run all tests with CICompatible tag
=> ci compatible tests workflow

client/src/features/ui/auto-size-input/AutoSizeInput.tsx, client/src/pages/spectrogram/components/annotation/AnnotationList.tsx, client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx, client/src/utils/__tests__/rfFunctions.test.ts, client/src/utils/rfFunctions.ts
Fixes when frequencies does not exist
=> fix frequencies issue

client/src/features/ui/styles/ThemeSelector.tsx, client/src/hooks/useIQEngineRouter.tsx, client/src/pages/recordings-browser/RecordingsBrowser.tsx, client/src/pages/repo-browser/RepoBrowser.tsx
On staging there is weird rendering before the page initially loads.
This fixes that.
=> Fix initial loading

client/index.html
fixes cors for authenticated sites
=> fix manifest.json cors

client/src/pages/recordings-browser/File.tsx
Addd sas token to the urls in case it si present.
=> Adding sas token

client/src/App.tsx
Make sizing a bit nicer for demo
=> Fix sizing

client/src/pages/recordings-browser/File.tsx
Add url encode so it works with any signature.
=> Adding encoding of sig

plugins/Dockerfile, plugins/src/requirements.txt
Adds requirements.txt to dockerfile, '--break-system-packages' is needed because we are using debians image to download gnu radio but need to install the requirements.txt file
=> Add requirements.txt to dockerfile

client/src/pages/spectrogram/components/PluginsPane.tsx, client/src/pages/spectrogram/hooks/useGetPluginsComponents.tsx
This was driving me mad, so I fixed it.
=> fix annoying plugin bug

client/src/pages/spectrogram/SettingsPane.tsx
Gets rid of the errors in the settings pane
=> Fix settings key issue

api/handlers/metadata.py, api/tests/test_api.py, client/src/api/metadata/ApiClient.ts, client/src/api/metadata/BlobClient.ts, client/src/api/metadata/LocalClient.ts, client/src/api/metadata/MetadataClient.ts, client/src/api/metadata/Queries.ts, client/src/pages/recordings-browser/Directory.tsx, client/src/pages/recordings-browser/DirectoryNode.ts, client/src/pages/recordings-browser/File.tsx, client/src/pages/recordings-browser/RecordingsBrowser.tsx
Changing browser, to allow showing the recordinglist of a container with potentially millions of recordings, as long as there aren't too many in the same folder.
=> Change recoding browser

client/src/pages/About.tsx
=> About page content tweaks

.mega-linter.yml, api/database/database.py, api/database/datasource.py, api/handlers/datasources.py, api/handlers/iq.py, api/handlers/metadata.py, api/handlers/status.py, api/tests/test_metadata.py
Refactor databse to change the methods to a new fial and simplify
=> Refactor datasources

client/src/utils/sigmfMetadata.ts
Correcting so everything is using JPG instead od JPEG
=> Jpeg to jpg

api/database/config_repo.py, api/database/models.py, api/handlers/config.py, api/importer/all.py, api/importer/config.py, api/tests/test_api.py, api/tests/test_importer.py
Makes the feature flags come from the db
=> make-feature-flags-from-db

Makefile
=> new linting image

client/src/pages/admin/pages/__tests__/configuration.test.tsx, client/src/pages/admin/pages/configuration.tsx
Adds the feature flags to the config page
=> add feature flags to config

client/src/App.tsx, client/src/hooks/use-feature-flags.tsx, client/src/pages/admin/pages/__tests__/configuration.test.tsx, client/src/pages/admin/pages/configuration.tsx, client/src/pages/repo-browser/RepoBrowser.tsx
Adds friendly display name to feature flags
=> Add display name

api/handlers/metadata.py, client/src/api/iqdata/__tests__/Queries.test.tsx, client/src/api/metadata/__tests__/ApiClient.test.tsx, client/src/api/metadata/__tests__/LocalClient.test.tsx, client/src/pages/recordings-browser/AnnotationModal.tsx, client/src/pages/recordings-browser/File.tsx, client/src/pages/spectrogram/components/annotation/AnnotationList.tsx, client/src/pages/spectrogram/components/annotation/AnnotationViewer.tsx, client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.meta.json, client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx, client/src/pages/spectrogram/components/metadata/__tests__/MetaRaw.test.tsx, client/src/utils/__tests__/sigmfMetadata.test.ts, client/src/utils/__tests__/validators.test.annotations.json, client/src/utils/__tests__/validators.test.meta.json, client/src/utils/constants.ts, client/src/utils/parseMeta.ts, client/src/utils/plotlyTemplate.ts, client/src/utils/sigmfMetadata.ts, plugins/src/azure_functions/SpectrogramThumbnails/__init__.py, plugins/src/markos_detector/markos_detector.py, plugins/src/simple_detector/simple_detector.py, plugins/src/template_plugin/template_plugin.py
Also refactored to get rid of annotation[core:description]
=> Annotation pie chart

client/src/api/config/queries.ts, client/src/pages/admin/pages/configuration.tsx
Fixes config not updating without refresh
=> add configuration not updating correctly fix

api/database/models.py, api/handlers/config.py, api/tests/test_api.py, client/src/api/config/queries.ts, client/src/hooks/use-router.tsx, client/src/pages/UploadPage.tsx, client/src/pages/repo-browser/LocalFileBrowser.tsx, client/src/utils/FetchMoreDataSource.ts
This is for allowing public to upload their recordings to a triage container that will be specified in an env var as a SAS URL.  This page isn't linked to anywhere, but it will replace the text here-
=> Upload to triage container page

client/src/pages/admin/pages/__tests__/configuration.test.tsx
There was an async issue where the api changes hadn't been reflected so were overriding the click changes, have updated the test so it gets all the anticipated values from the api before clicking.
=> fix async config issue in test

client/src/pages/spectrogram/components/annotation/AnnotationList.tsx, client/src/pages/spectrogram/components/metadata/MetaViewer.tsx, client/src/pages/spectrogram/freq-selector.tsx, client/src/pages/spectrogram/spectrogram-page.tsx, client/src/pages/spectrogram/time-selector.tsx, client/src/utils/__tests__/rfFunctions.test.ts, client/src/utils/rfFunctions.ts, client/src/utils/sigmfMetadata.ts
The actual bug fix is the changes to sigmfMetadata.ts that force numbers to actually be numbers, in case the author accidently put a string in their metadata
=> Tofixed bug fix

client/src/features/ui/modal/Modal.tsx, client/src/features/ui/modal/__tests__/Modal.test.tsx, client/src/pages/admin/pages/__tests__/add-data-source.test.tsx, client/src/pages/admin/pages/__tests__/configuration.test.tsx, client/src/pages/admin/pages/add-data-source.tsx, client/src/pages/admin/pages/configuration.tsx, client/src/pages/spectrogram/components/annotation/Actions.tsx, client/src/pages/spectrogram/components/annotation/AnnotationViewer.tsx, client/src/pages/spectrogram/components/annotation/__tests__/Actions.test.tsx, client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx, client/src/pages/spectrogram/components/metadata/MetaRaw.tsx, client/src/pages/spectrogram/components/metadata/__tests__/MetaRaw.test.tsx
Cleans up some of the aria labels to make them more inline with accessibility guidelines
=> Clean up aria labels

plugins/Dockerfile
Improve plugins build time by using the base image.
=> Improving plugins build time

client/src/api/iqdata/ApiClient.ts, client/src/api/iqdata/BlobClient.ts, client/src/api/iqdata/LocalClient.ts, client/src/pages/spectrogram/spectrogram-page.tsx, client/src/utils/fetch-more-data-source.ts, client/src/utils/selector.ts
Small cleanup of the some files before creating the new spectrogram page.
=> Small cleanup

api/blob/azure_client.py, api/database/datasource_repo.py, api/database/metadata_repo.py, api/database/models.py
Correct sync code to import data.
=> Correct sync

client/src/api/iqdata/Queries.ts, client/src/pages/recording-view/components/ruler-side.tsx, client/src/pages/recording-view/components/ruler-top.tsx, client/src/pages/recording-view/hooks/__tests__/use-get-image.test.tsx, client/src/pages/recording-view/hooks/__tests__/use-spectrogram.test.tsx, client/src/pages/recording-view/hooks/use-get-image.tsx, client/src/pages/recording-view/hooks/use-spectrogram.tsx, client/src/pages/recording-view/recording-view.tsx, client/src/utils/test-functions.ts
Add basic rendering od the image in the new spectrogram page
This page still ahve some debug information to help while developing it. This pr does add back the rulers.
=> Render image

client/src/api/iqdata/Queries.ts, client/src/pages/recording-view/components/ruler-side.tsx, client/src/pages/recording-view/components/ruler-top.tsx, client/src/pages/recording-view/hooks/__tests__/use-spectrogram.test.tsx, client/src/pages/recording-view/hooks/use-get-image.tsx, client/src/pages/recording-view/hooks/use-spectrogram-context.tsx, client/src/pages/recording-view/hooks/use-spectrogram.tsx, client/src/pages/recording-view/recording-view.tsx
Moving to text to acoid prop drilling when changing properties
=> Moving tro context to avoid prop drilling

client/src/pages/recording-view/components/plugins-pane.tsx, client/src/pages/recording-view/components/settings-pane.tsx, client/src/pages/recording-view/components/sidebar.tsx, client/src/pages/recording-view/hooks/use-spectrogram-context.tsx, client/src/pages/recording-view/recording-view.tsx
Added new sidebar Still need to adjust plugins pane and downlaod data.
=> New sidebar

client/src/pages/recording-view/components/__tests__/global-properties.test.tsx, client/src/pages/recording-view/components/__tests__/meta-raw.test.tsx, client/src/pages/recording-view/components/__tests__/meta-viewer.test.tsx, client/src/pages/recording-view/components/global-properties.tsx, client/src/pages/recording-view/components/meta-raw.tsx, client/src/pages/recording-view/components/meta-viewer.tsx, client/src/pages/recording-view/recording-view.tsx
Add global metadara componentes to the basic page
=> Global metadata

client/src/pages/recording-view/components/annotation/__tests__/actions.test.tsx, client/src/pages/recording-view/components/annotation/__tests__/annotation-list.test.meta.json, client/src/pages/recording-view/components/annotation/__tests__/annotation-list.test.tsx, client/src/pages/recording-view/components/annotation/actions.tsx, client/src/pages/recording-view/components/annotation/annotation-list.tsx, client/src/pages/recording-view/components/annotation/annotation-viewer.tsx, client/src/pages/recording-view/recording-view.tsx
=> Annotations

api/handlers/iq.py, client/src/pages/recording-view/components/__tests__/global-properties.test.tsx, client/src/pages/recording-view/components/scroll-bar.tsx, client/src/pages/recording-view/components/settings-pane.tsx, client/src/pages/recording-view/hooks/__tests__/use-spectrogram.test.tsx, client/src/pages/recording-view/hooks/use-spectrogram-context.tsx, client/src/pages/recording-view/hooks/use-spectrogram.tsx, client/src/pages/recording-view/recording-view.tsx
Adding scroll bar to the new spectgrogram page
=> Scroll bar

client/src/pages/recording-view/components/settings-pane.tsx, client/src/pages/recording-view/components/sidebar.tsx, client/src/pages/recording-view/components/time-selector.tsx, client/src/pages/recording-view/hooks/use-cursor-context.tsx, client/src/pages/recording-view/recording-view.tsx, e2e/__tests__/confirm_gnuradio.spec.ts
=> Add time cursor

client/src/hooks/use-query-client.tsx, client/src/pages/recording-view/components/annotation/annotation-list.tsx, client/src/pages/recording-view/components/annotation/annotation-viewer.tsx, client/src/pages/recording-view/components/scroll-bar.tsx, client/src/pages/recording-view/hooks/use-spectrogram-context.tsx, client/src/pages/recording-view/recording-view.tsx
Correcting annotatioon viwer to the new format and correcting the calculations.
=> Correcting annotation viewer

client/src/hooks/use-query-client.tsx, client/src/pages/recording-view/components/scroll-bar.tsx, client/src/pages/recording-view/components/time-selector-minimap.tsx, client/src/pages/recording-view/recording-view.tsx
=> Adding back time selector minimap

client/src/pages/recording-view/recording-view.tsx
Add resizing to the current spectrogram.
=> Add resize to recording view

client/src/pages/recording-view/components/settings-pane.tsx
=> add save selected samples

client/src/pages/recording-view/components/plugins-pane.tsx, client/src/pages/spectrogram/components/PluginsPane.tsx
Duplicates the feature added to PluginsPane in the recording view
=> Add annotation to plugin for recording view

client/src/pages/recording-view/components/scroll-bar.tsx, client/src/pages/recording-view/recording-view.tsx
Fixes the scroll bar bug where it goes beyond the end of file
=> fix scrolling after end of file bug

.vscode/launch.json, client/src/api/iqdata/Queries.ts, client/src/api/metadata/queries.ts, client/src/pages/recording-view/components/scroll-bar.tsx, client/src/pages/recording-view/hooks/__tests__/use-spectrogram.test.tsx, client/src/pages/recording-view/hooks/use-spectrogram.tsx, client/src/utils/constants.ts
Add download tiles to the spectrogram page to show the current downloaded tiles.
=> Adding list for downloaded tiles

client/src/api/iqdata/Queries.ts, client/src/mocks/setup-tests.tsx, client/src/pages/recording-view/components/settings-pane.tsx, client/src/pages/recording-view/hooks/use-spectrogram.tsx
Addin support for pyodide and taps also changing to use callback and queries for current data using the React query selector.
=> Adding pyodide and taps

client/src/pages/recording-view/components/plugins-pane.tsx
Fix current plugins to enable them again
=> Fix plugins

client/src/pages/recording-view/components/settings-pane.tsx
Small bug that was going over the space of the plugin pane.
This was making me go insane...
=> Small fix for the size of plugins

api/handlers/iq.py, api/tests/test_iq_api.py
Adds SASToken to iq-data calls that require it.
Corrects iq-data tests
=> IQ-data sastoken fix

client/src/pages/recording-view/components/plugins-pane.tsx
Correct the plugins to send the correct data and calculate the return back correctly.
=> Correct sending plugin data

client/src/pages/recording-view/hooks/use-spectrogram.tsx
Fixed Annotations not matching current positioning of annotations
=> Correcting spetrogram display to meet annottions

client/src/api/metadata/api-client.ts, client/src/pages/metadata-query/geo/geo-query.tsx, client/src/pages/metadata-query/metadata-query.tsx
inverts lon, lat as per GeoJSON spec as leaflet expects lat-lon - for track overlay
=> invert long/lat from GeoJSON specification to speak leaflet - track data

.github/workflows/scorecard.yml
=> Added openssf scorecard action

README.md
=> Added openssf scorecard badge

client/src/pages/recording-view/components/annotation/annotation-viewer.tsx, client/src/pages/recording-view/recording-view.tsx
Fixes the Add Annotation bug ensuring that when Add Annotation is clicked, the annotation box appears on the spectrogram immediately.
=> Fix Add Annotation

client/src/pages/recording-view/components/annotation/annotation-viewer.tsx, client/src/pages/recording-view/components/freq-selector.tsx, client/src/pages/recording-view/components/time-selector-minimap.tsx, client/src/pages/recording-view/components/time-selector.tsx
=> Misc visual fixes for annotations and selection bars

.github/workflows/run_staging_deployment.yml, plugins/src/plugins_api.py
=> added plugin auto deploy to staging

client/package-lock.json, client/package.json
=> removed snowpack which was unused

client/src/pages/recording-view/components/plugins-pane.tsx
Ensures cursors error only happens when cursor is selected for the plugins.
=> Fix cursor error

plugins/src/plugins_api.py
=> fixed plugins that broken when azure function dir was deleted

api/requirements.txt
=> added back aiohttp

.github/linters/.pylintrc, .github/workflows/linter.yml, api/main.py
so it doesnt conflict with our actual docs, when we run api and client on the same port
=> Move api docs endpoint to api_docs

client/src/pages/recording-view/components/freq-selector.tsx
=> RF toggle is now included in the freq selection bar text

plugins/src/fm_signal_detector/fm_signal_detector.py
=> Created plugin that detects FM radio signals

plugins/src/requirements.txt
=> added pydantic to plugins requirements

client/src/pages/admin/admin.tsx, client/src/pages/admin/pages/plugins.tsx
=> Add plugin fix

client/package-lock.json, client/package.json, client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Fixes the annotation viewer bug that made the annotation label stay in view when going to home page.
=> Fix annotation viewer label staying in place when going to home page

plugins/src/plugins_api.py
=> Ignore the models dir when finding available plugins

api/handlers/metadata.py, client/src/api/datasource/api-client.ts, client/src/api/datasource/datasource-client-factory.ts, client/src/api/datasource/queries.ts, client/src/api/iqdata/ApiClient.ts, client/src/api/iqdata/IQDataClient.ts, client/src/api/iqdata/IQDataClientFactory.ts, client/src/api/iqdata/Queries.ts, client/src/api/metadata/api-client.ts, client/src/api/metadata/blob-client.ts, client/src/api/metadata/metadata-client-factory.ts, client/src/api/metadata/queries.ts, client/src/api/utils/Auth-Utils.ts, client/src/api/utils/AuthUtils.ts
Refactors api client factories and queries.ts to ensure valid hook calls.
Removes authorization check on thumbnail api.
=> RBAC Refactor

client/src/pages/recording-view/components/annotation/__tests__/actions.test.tsx, client/src/pages/recording-view/components/annotation/actions.tsx, client/src/pages/recording-view/components/annotation/annotation-viewer.tsx, client/src/utils/__tests__/sigmfMetadata.test.ts, client/src/utils/sigmfMetadata.ts
Adds hover for comments.
Removes null values in PR.
=> Add annotation improvements

client/src/api/iqdata/Queries.ts, client/src/api/utils/Auth-Utils.ts, client/src/pages/recording-view/hooks/use-cursor-context.tsx
Adding a limitation of around 1MB for download size per each time that we do call the api backend
This was caising a problem for very larger cursors
=> 🚧 Adding a limitation of around 1MB

client/src/pages/metadata-query/__tests__/band-selection.test.tsx, client/src/pages/metadata-query/__tests__/band.test.tsx, client/src/pages/metadata-query/freq-query.tsx
Removes VLF and LF, and adds everything up to and including Ka band for the queries.
=> Change frequency selection

.eslintrc.yml, client/src/api/datasource/queries.ts
Adds missing MSAL instance to DataSourceClientFactory call in useSasToken.
=> Add missing msal instance

.github/workflows/run_playwright_tests.yml, client/src/pages/recording-view/components/frequency-plot.tsx, client/src/pages/recording-view/components/iq-plot.tsx, client/src/pages/recording-view/components/time-plot.tsx
=> Fixed time iq freq width and height

client/src/pages/upload-page.tsx
=> Better upload page

README.md, client/src/pages/docs/admin-page.mdx, client/src/pages/docs/backend.mdx, client/src/pages/docs/config-feature-flags.mdx, client/src/pages/docs/docs-pages.tsx, client/src/pages/docs/frontend.mdx, client/src/pages/docs/new-developer-guide.mdx, client/src/pages/docs/overview.mdx
Preview new readme: https://github.com/IQEngine/IQEngine/tree/update-readme
=> Shuffled content from readme into the docs pages

.gitignore, client/src/api/iqdata/BlobClient.ts, client/src/api/iqdata/Queries.ts, client/src/pages/recording-view/components/scroll-bar.tsx, client/src/pages/recording-view/hooks/use-spectrogram-context.tsx, client/src/pages/recording-view/hooks/use-spectrogram.tsx, client/src/utils/__tests__/group.test.ts, client/src/utils/group.ts
Fix the time taken to group continous indexes
=> Fix python snippet delay

.vscode/settings.json, api/aifunctions/aiquery.py, api/database/metadata_repo.py, api/database/models.py, api/handlers/config.py, api/handlers/metadata.py, api/requirements.txt, api/tests/test_api.py
=> Open AI Query

client/src/pages/metadata-query/__tests__/freq-query.test.tsx, client/src/pages/metadata-query/freq-query.tsx
Fixes the bug for when unable to query on freq page.
=> Fix the bug for when unable to query on freq page.

client/src/api/datasource/api-client.ts
Small fix to incorrect function reference.
=> Missing reference

client/src/pages/landing-page/landing-page.tsx
Fix landing page bug where page is displaying empty
=> Fix landing page bug where page is displaying empty

client/src/api/datasource/api-client.ts, client/src/api/iqdata/Queries.ts
Resolve return type issue in fetch rawiqdata
=> Return Type fix for rawiqdata

.vscode/settings.json, client/src/api/Models.ts, client/src/api/metadata/api-client.ts, client/src/api/metadata/blob-client.ts, client/src/api/metadata/local-client.ts, client/src/api/metadata/metadata-client.ts, client/src/api/metadata/queries.ts, client/src/hooks/use-query-client.tsx, client/src/hooks/use-router.tsx, client/src/pages/repo-browser/repo-browser.tsx, client/src/pages/repo-browser/smart-query-tile.tsx, client/src/pages/smart-query/smart-query.tsx
=> OpenQuery frontend

client/src/pages/smart-query/smart-query.tsx
Correcting the visuals of smart query
=> Correcting visuals smart query

client/src/pages/recording-view/components/ruler-side.tsx
fixed the calculation for tick labels on the vertical ruler. They were correct at position zero, but the further you scroll, the more they vary from correct values.
=> fix y coordinate calculation

client/src/pages/recording-view/components/annotation/annotation-viewer.tsx, client/src/pages/recording-view/components/plugins-pane.tsx
Fixes cloud pointer and issue where annotations were overflowing.
=> Fix local cloud pointer and annotations overflow

client/src/utils/selector.ts
=> Loading is now gray instead of yellow

client/src/utils/validators.ts
added ajv formats to validator - fixes warnings for uuid and uri formats in sigmf schema validation
=> fix validation warnings

.vscode/settings.json, Makefile, api/handlers/iq.py, client/package.json, client/src/api/iqdata/ApiClient.ts, client/src/api/iqdata/Queries.ts
see the `Queries.ts` diff for the bug fix, rest is comments and such
=> Fixed nasty bug involving *2 missing for iqdata fetch

e2e/common-steps.ts
=> Fixed e2e tests now that theres 2 browse buttons

client/src/pages/recording-view/components/scroll-bar.tsx
fixes microscopic bug with data loaded indicator
array.find returns the found index, not a boolean. if the found index is zero, it's falsy, so the existing code is broken in that case.
=> fix data loaded indicator

client/src/pages/recording-view/components/scroll-bar.tsx
0 is not null, but it is falsey, so it breaks the conditional
=> fix bug in the fix

api/handlers/iq.py
=> Correct account key

client/src/pages/recording-view/components/__tests__/meta-viewer.test.tsx, client/src/pages/recording-view/components/meta-viewer.tsx
Makes the metadata properties shown on page smaller
=> Make the metadata properties shown on page smaller

client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Changes the annotation tooltip datatip to display below text and have the accent colour
=> make tooltip contrast better

client/src/app.tsx
Fixes margin for internal branding
=> Fix margins

client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Small alignment to the tooltip on the annotation viewer
* [x ] Have you successfully ran tests with your changes locally? Including container validation.
=> Add aligment issue to annotation viewer

client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Moves no wrap to just the paragraph:
Before:
After:
=> Move no wrap to the paragraph

client/src/pages/recording-view/components/plugins-pane.tsx
Add feedback when executing a plugin solves #641
=> giving feedback for plugin

client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Allows the middle of the annotation to be viewed if it is bigger than the screen, and prevents the annotation label to overflow.
=> Fix annotation viewer

client/src/pages/recording-view/components/annotation/annotation-viewer.tsx, client/src/utils/__tests__/sigmfMetadata.test.ts, client/src/utils/sigmfMetadata.ts
Truncates comment if over so many characters
=> Truncate comment on spectrogram

plugins/Dockerfile
=> Add paralelism to plugins

plugins/src/plugins_api.py
printing value and general errors in the terminal
=> Update plugins_api.py minor enhancement

plugins/src/gain_stage/gain_stage.py
Added gain stage plugin
Parameters: gain (float)
Action: each sample will be multiplied by the gain parameter value
=> gain stage plugin feature

api/database/datasource_repo.py, api/handlers/datasources.py
Updates the sync process to include the preferred username for entry into the versions collection on creation of new metadata documents for the purpose of audit.
=> Add user name to sync for versions audit entry

api/requirements.txt
=> bump cryptography to latest

.github/workflows/linter.yml
=> linter continue-on-error: true

client/src/api/iqdata/BlobClient.ts, client/src/pages/recording-view/components/plugins-pane.tsx
fixes #738 
also fixes #739 although it still takes a weirdly long time for the minimap to load when using custom azure blob account
=> Disable use cloud option for plugins for private blob accounts

api/app/converter_router.py, api/converters/README.md, api/converters/wav_to_sigmf.py, client/src/pages/converter/converter.tsx, client/src/pages/sigmf.tsx
@romanziske mind reviewing this?  since it lays the framework for other converters.  I actually found it super useful to call directly from python when I had to convert some 4GB local files from wav to SigMF earlier today.
=> Moved wav-to-sigmf converter to separate file and sped it up

api/app/iq_router.py, api/helpers/urlmapping.py, client/src/utils/sigmfMetadata.ts
instead of opening it in browser
=> Download meta file when clicking the link

api/app/config.py, api/app/database.py, api/app/datasources.py, api/app/iq_router.py, api/helpers/urlmapping.py, api/main.py, client/package-lock.json, client/package.json, client/src/api/iqdata/Queries.ts, client/src/pages/recording-view/components/frequency-plot.tsx, client/src/pages/recording-view/components/ruler-top.tsx, client/src/pages/recording-view/components/settings-pane.tsx, client/src/pages/recording-view/hooks/use-spectrogram-context.tsx, client/src/pages/recording-view/hooks/use-spectrogram.tsx, client/src/utils/fetch-more-data-source.ts, client/src/utils/sigmfMetadata.ts
- download meta file when clicking the link in recordings list
- spectrogram settings option to square signal (clientside)
- freq plot now shows the actual freq for x-axis
- bumped vite to latest
- possibly fixed issue with duplicates during sync
=> Several minor features/fixes

Makefile, client/package-lock.json, client/package.json, client/src/hooks/use-router.tsx, client/src/pages/browser/browser.tsx, client/src/pages/browser/custom-azure-form.tsx, client/src/pages/landing-page/landing-page.tsx, client/src/pages/validator.tsx, client/src/utils/selector.ts, client/src/utils/validators.ts, e2e/__tests__/azure_blob_datasource.spec.ts, e2e/__tests__/confirm_API_data_browse.spec.ts, e2e/__tests__/confirm_api_datasource.spec.ts, e2e/__tests__/confirm_blob_datasource.spec.ts, e2e/__tests__/confirm_estevez.spec.ts, e2e/__tests__/confirm_gnuradio.spec.ts, e2e/__tests__/confirm_siggen_card.spec.ts, e2e/__tests__/confirm_validator_card.spec.ts, e2e/__tests__/confirm_wav_converter.spec.ts, e2e/__tests__/siggen.spec.ts
=> Fix integration test flakiness

client/src/pages/docs/docs-pages.tsx, client/src/pages/docs/record-from-sdr.mdx
Still need many more SDRs added, and the CSS associated with the code snippets looks like crap when the markdown is rendered-
=> Start to the "record with SDR" reference docs page

client/src/api/iqdata/IQDataClientFactory.ts, client/src/api/iqdata/Queries.ts, client/src/api/metadata/api-client.ts, client/src/api/metadata/metadata-client-factory.ts, client/src/api/metadata/queries.ts
When trying to get the information for the IQData and Metadata, an error was being thrown because the token was returning a bad request.
This was because an 'undefined' scope was being passed to it.
I have updated the code to pass the correct configuration in.
=> Fix authentication of query page

api/app/iq_router.py
=> Allow downloading data and meta for local filesource
